# Generated by Django 2.0 on 2018-11-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='artiste_nom',
            field=models.CharField(default='x', max_length=70),
        ),
    ]
