# Generated by Django 2.1.3 on 2018-11-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations_app', '0002_r_artiste_documents_comment_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r_artiste_documents',
            name='comment_relations',
        ),
    ]
