# Generated by Django 2.0 on 2018-11-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations_app', '0002_auto_20181120_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='artiste_nomjpg',
        ),
        migrations.AlterField(
            model_name='artiste',
            name='artiste_nom',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
