# Generated by Django 2.1.3 on 2018-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations_app', '0003_remove_r_artiste_documents_comment_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='artiste_nomjpg',
            field=models.CharField(max_length=500),
        ),
    ]
