# Generated by Django 2.1.3 on 2018-11-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations_app', '0004_auto_20181123_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='artiste_nomjpg',
            field=models.CharField(default='nom_artiste', max_length=500),
        ),
    ]
